<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_app_description'] = 'Приложение "Почта" является очень простой библиотекой, которая обрабатывает основные параметры почты для других почтовых приложений.';
$lang['mail_app_name'] = 'Библиотека почты';
$lang['mail_attachment_file_not_found'] = 'Attachment not found.';
$lang['mail_attachment_invalid'] = 'Attachment is invalid.';
$lang['mail_bounce'] = 'Bounce';
$lang['mail_discard'] = 'Discard';
$lang['mail_encryption'] = 'Encryption';
$lang['mail_encryption_invalid'] = 'SMTP encryption is invalid.';
$lang['mail_mail_domain'] = 'Почтовый домен';
$lang['mail_mail_domain_already_exists'] = 'Mail domain already exists.';
$lang['mail_mail_domain_invalid'] = 'Почтовый домен является недействительным.';
$lang['mail_mail_hostname'] = 'Mail Hostname';
$lang['mail_none'] = 'None';
$lang['mail_notification_test'] = 'Notification Test';
$lang['mail_pass_through'] = 'Pass Through';
$lang['mail_recipient_invalid'] = 'Recipient is invalid.';
$lang['mail_recipient_not_set'] = 'Recipient not set.';
$lang['mail_send_failed'] = 'Send failed.';
$lang['mail_send_now'] = 'Send Now';
$lang['mail_send_to'] = 'Send To';
$lang['mail_sender_address'] = 'Sender Address';
$lang['mail_smtp_hostname'] = 'SMTP Hostname/IP';
$lang['mail_smtp_notification_settings'] = 'SMTP/E-mail Notification Settings';
$lang['mail_smtp_password'] = 'SMTP Password';
$lang['mail_smtp_password_invalid'] = 'SMTP password is invalid.';
$lang['mail_smtp_port'] = 'SMTP Port';
$lang['mail_smtp_username'] = 'SMTP Username';
$lang['mail_smtp_username_invalid'] = 'SMTP username is invalid.';
$lang['mail_ssl'] = 'SSL';
$lang['mail_subject_invalid'] = 'Subject is invalid.';
$lang['mail_test'] = 'Test';
$lang['mail_test_success_message'] = 'Congratulations.  The mail notification test was successful.';
$lang['mail_test_was_successful'] = 'Mail test was successful.';
$lang['mail_tls'] = 'TLS';
$lang['mail_update_and_test'] = 'Update and Test';
