<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['mail_app_description'] = 'Aplikacja pocztowa dostarcza opcji do konfiguracji powiadomień oraz obsługę prostego serwera pocztowego.';
$lang['mail_app_name'] = 'Ustawienia poczty';
$lang['mail_attachment_file_not_found'] = 'Nie znaleziono załącznika.';
$lang['mail_attachment_invalid'] = 'Załącznik jest nieprawidłowy';
$lang['mail_bounce'] = 'Odbicie';
$lang['mail_discard'] = 'Odrzucenie';
$lang['mail_encryption'] = 'Szyfrowanie';
$lang['mail_encryption_invalid'] = 'Szyfrowanie SMTP jest nieprawidłowe.';
$lang['mail_mail_domain'] = 'Domena Poczty';
$lang['mail_mail_domain_already_exists'] = 'Domena pocztowa już istnieje.';
$lang['mail_mail_domain_invalid'] = 'Domena pocztowa jest nieprawidłowa.';
$lang['mail_mail_hostname'] = 'Nazwa hosta poczty';
$lang['mail_none'] = 'Brak';
$lang['mail_notification_test'] = 'Test powiadomienia';
$lang['mail_pass_through'] = 'Przepuść';
$lang['mail_recipient_invalid'] = 'Odbiorca jest nieprawidłowy.';
$lang['mail_recipient_not_set'] = 'Nie ustawiono odbiorcy.';
$lang['mail_send_failed'] = 'Wysyłanie nie powiodło się.';
$lang['mail_send_now'] = 'Wyślij teraz';
$lang['mail_send_to'] = 'Wyślij do';
$lang['mail_sender_address'] = 'Adres nadawcy';
$lang['mail_smtp_hostname'] = 'Nazwa hosta SMTP/IP';
$lang['mail_smtp_notification_settings'] = 'Ustawienia powiadomień SMTP/E-mail';
$lang['mail_smtp_password'] = 'Hasło SMTP';
$lang['mail_smtp_password_invalid'] = 'Hasło SMTP jest nieprawidłowe.';
$lang['mail_smtp_port'] = 'Port SMTP';
$lang['mail_smtp_username'] = 'Nazwa użytkownika SMTP';
$lang['mail_smtp_username_invalid'] = 'Nazwa użytkownika SMTP jest nieprawidłowa.';
$lang['mail_ssl'] = 'SSL';
$lang['mail_subject_invalid'] = 'Temat jest nieprawidłowy.';
$lang['mail_test'] = 'Test';
$lang['mail_test_success_message'] = 'Gratulacje.  Test powiadomień poczty powiódł się.';
$lang['mail_test_was_successful'] = 'Test poczty powiódł się.';
$lang['mail_tls'] = 'TLS';
$lang['mail_update_and_test'] = 'Uaktualnij i sprawdź';
